/* 
 * This file is part of the uv_hal distribution (www.usevolt.fi).
 * Copyright (c) 2017 Usevolt Oy.
 * 
 * This program is free software: you can redistribute it and/or modify  
 * it under the terms of the GNU General Public License as published by  
 * the Free Software Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful, but 
 * WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License 
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
*/


#ifndef CAN_ICU_H_
#define CAN_ICU_H_


/// @file: Defines the UW ceiling supply board CANopen interface.

#include <stdint.h>






#define ICU_NODE_ID					0xA






/// @brief: Defines all ICU's EMCY message data values.
/// All EMCY messages belong to device specific EMCY error code category (0xFF00)
typedef enum {
	ICU_EMCY_BLADEOPEN_OVERCURRENT = (ICU_NODE_ID << 16),
	ICU_EMCY_BLADEOPEN_FAULT,
	ICU_EMCY_FEEDOPEN_OVERCURRENT,
	ICU_EMCY_FEEDOPEN_FAULT,
	ICU_EMCY_SAW_OVERCURRENT,
	ICU_EMCY_SAW_FAULT,
	ICU_EMCY_TILT_OVERCURRENT,
	ICU_EMCY_TILT_FAULT,
	ICU_EMCY_FEEDSERIES_OVERCURRENT,
	ICU_EMCY_FEEDSERIES_FAULT,
	ICU_EMCY_TILTFLOAT_OVERCURRENT,
	ICU_EMCY_TILTFLOAT_FAULT,
	ICU_EMCY_COUNT
} icu_emcy_e;


/// @brief: Fuzzy logic level structure. As this is mapped to object dictionary,
/// this should be 32-bits in total size
typedef struct {
	// distance from the target when this level applies. When the actual distance to target is below
	// this, the fuzzy logic level is increased
	uint16_t dist_mm;
	// feeding speed on this level
	uint8_t max_speed;
	uint8_t _unused;
} icu_feed_fl_st;


typedef enum {
	ICU_FEED_STATE_OFF = 0,
	ICU_FEED_STATE_MANUAL,
	ICU_FEED_STATE_ON,
	ICU_FEED_STATE_TARGET_REACHED,
	ICU_FEED_STATE_TARGET_UNREACHED
} icu_feed_states_e;


enum {
	ICU_TILT_DIR_UP,
	ICU_TILT_DIR_DOWN
};
typedef uint8_t icu_tilt_dir_e;


// ICU OBJECT DICTIONARY ENTRIES


#define ICU_TOTAL_CURRENT_INDEX					0x2000
#define ICU_TOTAL_CURRENT_SUBINDEX				0
#define ICU_TOTAL_CURRENT_TYPE					CANOPEN_UNSIGNED16
#define ICU_TOTAL_CURRENT_PERMISSIONS			CANOPEN_RO

#define ICU_IMPL1_REQ_INDEX						0x2100
#define ICU_IMPL1_REQ_SUBINDEX					0
#define ICU_IMPL1_REQ_TYPE						CANOPEN_SIGNED8
#define ICU_IMPL1_REQ_PERMISSIONS				CANOPEN_RO

#define ICU_IMPL2_REQ_INDEX						0x2101
#define ICU_IMPL2_REQ_SUBINDEX					0
#define ICU_IMPL2_REQ_TYPE						CANOPEN_SIGNED8
#define ICU_IMPL2_REQ_PERMISSIONS				CANOPEN_RO

#define ICU_BLADEOPEN_REQ_INDEX					0x2200
#define ICU_BLADEOPEN_REQ_SUBINDEX				0
#define ICU_BLADEOPEN_REQ_TYPE					CANOPEN_SIGNED8
#define ICU_BLADEOPEN_REQ_PERMISSIONS			CANOPEN_RW

#define ICU_BLADEOPEN_PARAM_INDEX				0x2201
#define ICU_BLADEOPEN_PARAM_ARRAY_MAX_SIZE		6
#define ICU_BLADEOPEN_PARAM_TYPE				CANOPEN_ARRAY16
#define ICU_BLADEOPEN_PARAM_PERMISSIONS			CANOPEN_RW

#define ICU_BLADEOPEN_CURRENT_INDEX				0x2202
#define ICU_BLADEOPEN_CURRENT_SUBINDEX			0
#define ICU_BLADEOPEN_CURRENT_TYPE				CANOPEN_UNSIGNED16
#define ICU_BLADEOPEN_CURRENT_PERMISSIONS		CANOPEN_RO

#define ICU_FEEDOPEN_REQ_INDEX					0x2210
#define ICU_FEEDOPEN_REQ_SUBINDEX				0
#define ICU_FEEDOPEN_REQ_TYPE					CANOPEN_SIGNED8
#define ICU_FEEDOPEN_REQ_PERMISSIONS			CANOPEN_RW

#define ICU_FEEDOPEN_PARAM_INDEX				0x2211
#define ICU_FEEDOPEN_PARAM_ARRAY_MAX_SIZE		6
#define ICU_FEEDOPEN_PARAM_TYPE					CANOPEN_ARRAY16
#define ICU_FEEDOPEN_PARAM_PERMISSIONS			CANOPEN_RW

#define ICU_FEEDOPEN_CURRENT_INDEX				0x2212
#define ICU_FEEDOPEN_CURRENT_SUBINDEX			0
#define ICU_FEEDOPEN_CURRENT_TYPE				CANOPEN_UNSIGNED16
#define ICU_FEEDOPEN_CURRENT_PERMISSIONS		CANOPEN_RO

#define ICU_SAW_REQ_INDEX						0x2220
#define ICU_SAW_REQ_SUBINDEX					0
#define ICU_SAW_REQ_TYPE						CANOPEN_SIGNED8
#define ICU_SAW_REQ_PERMISSIONS					CANOPEN_RW

#define ICU_SAW_PARAM_INDEX						0x2221
#define ICU_SAW_PARAM_ARRAY_MAX_SIZE			6
#define ICU_SAW_PARAM_TYPE						CANOPEN_ARRAY16
#define ICU_SAW_PARAM_PERMISSIONS				CANOPEN_RW

#define ICU_SAW_CURRENT_INDEX					0x2222
#define ICU_SAW_CURRENT_SUBINDEX				0
#define ICU_SAW_CURRENT_TYPE					CANOPEN_UNSIGNED16
#define ICU_SAW_CURRENT_PERMISSIONS				CANOPEN_RO

#define ICU_SAW_IN_INDEX						0x2223
#define ICU_SAW_IN_SUBINDEX						0
#define ICU_SAW_IN_TYPE							CANOPEN_UNSIGNED8
#define ICU_SAW_IN_PERMISSIONS					CANOPEN_RO

#define ICU_TILT_REQ_INDEX						0x2230
#define ICU_TILT_REQ_SUBINDEX					0
#define ICU_TILT_REQ_TYPE						CANOPEN_SIGNED8
#define ICU_TILT_REQ_PERMISSIONS				CANOPEN_RW

#define ICU_TILT_REQ2_INDEX						0x2230
#define ICU_TILT_REQ2_SUBINDEX					1
#define ICU_TILT_REQ2_TYPE						CANOPEN_SIGNED8
#define ICU_TILT_REQ2_PERMISSIONS				CANOPEN_RW

#define ICU_TILT_PARAM_INDEX					0x2231
#define ICU_TILT_PARAM_ARRAY_MAX_SIZE			6
#define ICU_TILT_PARAM_TYPE						CANOPEN_ARRAY16
#define ICU_TILT_PARAM_PERMISSIONS				CANOPEN_RW

#define ICU_TILT_CURRENT_INDEX					0x2232
#define ICU_TILT_CURRENT_SUBINDEX				0
#define ICU_TILT_CURRENT_TYPE					CANOPEN_UNSIGNED16
#define ICU_TILT_CURRENT_PERMISSIONS			CANOPEN_RO

#define ICU_TILT_DIR_INDEX						0x2233
#define ICU_TILT_DIR_SUBINDEX					0
#define ICU_TILT_DIR_TYPE						CANOPEN_UNSIGNED8
#define ICU_TILT_DIR_PERMISSIONS				CANOPEN_RO

#define ICU_TILTFLOAT_STATUS_INDEX				0x2234
#define ICU_TILTFLOAT_STATUS_SUBINDEX			0
#define ICU_TILTFLOAT_STATUS_TYPE				CANOPEN_UNSIGNED8
#define ICU_TILTFLOAT_STATUS_PERMISSIONS		CANOPEN_RO

#define ICU_TILTFLOAT_CURRENT_INDEX				0x2235
#define ICU_TILTFLOAT_CURRENT_SUBINDEX			0
#define ICU_TILTFLOAT_CURRENT_TYPE				CANOPEN_UNSIGNED16
#define ICU_TILTFLOAT_CURRENT_PERMISSIONS		CANOPEN_RO

#define ICU_TILTFLOAT_ENABLE_INDEX				0x2236
#define ICU_TILTFLOAT_ENABLE_SUBINDEX			0
#define ICU_TILTFLOAT_ENABLE_TYPE				CANOPEN_UNSIGNED8
#define ICU_TILTFLOAT_ENABLE_PERMISSIONS		CANOPEN_RW

#define ICU_TILT_ONTHUMB_STATUS_INDEX			0x2237
#define ICU_TILT_ONTHUMB_STATUS_SUBINDEX		0
#define ICU_TILT_ONTHUMB_STATUS_TYPE			CANOPEN_UNSIGNED8
#define ICU_TILT_ONTHUMB_STATUS_PERMISSIONS		CANOPEN_RO

#define ICU_FEED_REQ_INDEX						0x2240
#define ICU_FEED_REQ_SUBINDEX					0
#define ICU_FEED_REQ_TYPE						CANOPEN_SIGNED8
#define ICU_FEED_REQ_PERMISSIONS				CANOPEN_RW

#define ICU_FEED_PARAM_INDEX					0x2241
#define ICU_FEED_PARAM_ARRAY_MAX_SIZE			8
#define ICU_FEED_PARAM_TYPE						CANOPEN_ARRAY16
#define ICU_FEED_PARAM_PERMISSIONS				CANOPEN_RW

#define ICU_FEED_CURRENT_INDEX					0x2242
#define ICU_FEED_CURRENT_SUBINDEX				0
#define ICU_FEED_CURRENT_TYPE					CANOPEN_UNSIGNED16
#define ICU_FEED_CURRENT_PERMISSIONS			CANOPEN_RO

#define ICU_ALLOPEN_REQ_INDEX					0x2250
#define ICU_ALLOPEN_REQ_SUBINDEX				0
#define ICU_ALLOPEN_REQ_TYPE					CANOPEN_SIGNED8
#define ICU_ALLOPEN_REQ_PERMISSIONS				CANOPEN_RW

#define ICU_ALLOPEN_PARAM_INDEX					0x2251
#define ICU_ALLOPEN_PARAM_ARRAY_MAX_SIZE		7
#define ICU_ALLOPEN_PARAM_TYPE					CANOPEN_ARRAY16
#define ICU_ALLOPEN_PARAM_PERMISSIONS			CANOPEN_RW


#define ICU_LENGTH_UM_INDEX						0x2300
#define ICU_LENGTH_UM_SUBINDEX					0
#define ICU_LENGTH_UM_TYPE						CANOPEN_SIGNED32
#define ICU_LENGTH_UM_PERMISSIONS				CANOPEN_RO

#define ICU_TARGET_LEN_UM_INDEX					0x2301
#define ICU_TARGET_LEN_UM_SUBINDEX				0
#define ICU_TARGET_LEN_UM_TYPE					CANOPEN_SIGNED32
#define ICU_TARGET_LEN_UM_PERMISSIONS			CANOPEN_RW

#define ICU_LEN_CALIB_INDEX						0x2302
#define ICU_LEN_CALIB_SUBINDEX					0
#define ICU_LEN_CALIB_TYPE						CANOPEN_UNSIGNED16
#define ICU_LEN_CALIB_PERMISSIONS				CANOPEN_RW

#define ICU_LEN_STATE_INDEX						0x2303
#define ICU_LEN_STATE_SUBINDEX					0
#define ICU_LEN_STATE_TYPE						CANOPEN_UNSIGNED8
#define ICU_LEN_STATE_PERMISSIONS				CANOPEN_RO

#define ICU_LEN_FL_INDEX						0x2304
#define ICU_LEN_FL_ARRAY_SIZE					3
#define ICU_LEN_FL_TYPE							CANOPEN_ARRAY32
#define ICU_LEN_FL_PERMISSIONS					CANOPEN_RW

#define ICU_WIDTH_MM_INDEX						0x2305
#define ICU_WIDTH_MM_SUBINDEX					0
#define ICU_WIDTH_MM_TYPE						CANOPEN_UNSIGNED16
#define ICU_WIDTH_MM_PERMISSIONS				CANOPEN_RO

#define ICU_WIDTH_RAW1_INDEX					0x2305
#define ICU_WIDTH_RAW1_SUBINDEX					1
#define ICU_WIDTH_RAW1_TYPE						CANOPEN_UNSIGNED16
#define ICU_WIDTH_RAW1_PERMISSIONS				CANOPEN_RO

#define ICU_WIDTH_RAW2_INDEX					0x2305
#define ICU_WIDTH_RAW2_SUBINDEX					2
#define ICU_WIDTH_RAW2_TYPE						CANOPEN_UNSIGNED16
#define ICU_WIDTH_RAW2_PERMISSIONS				CANOPEN_RO

#define ICU_WIDTH_REL_INDEX						0x2305
#define ICU_WIDTH_REL_SUBINDEX					3
#define ICU_WIDTH_REL_TYPE						CANOPEN_UNSIGNED16
#define ICU_WIDTH_REL_PERMISSIONS				CANOPEN_RO

#define ICU_WIDTH_CALIB_MIN_REQ_INDEX			0x2306
#define ICU_WIDTH_CALIB_MIN_REQ_SUBINDEX		0
#define ICU_WIDTH_CALIB_MIN_REQ_TYPE			CANOPEN_UNSIGNED8
#define ICU_WIDTH_CALIB_MIN_REQ_PERMISSIONS		CANOPEN_WO

#define ICU_WIDTH_CALIB_MAX_REQ_INDEX			0x2307
#define ICU_WIDTH_CALIB_MAX_REQ_SUBINDEX		0
#define ICU_WIDTH_CALIB_MAX_REQ_TYPE			CANOPEN_UNSIGNED8
#define ICU_WIDTH_CALIB_MAX_REQ_PERMISSIONS		CANOPEN_WO

#define ICU_WIDTH_CALIB_REQ_INDEX				0x2308
#define ICU_WIDTH_CALIB_REQ_SUBINDEX			0
#define ICU_WIDTH_CALIB_REQ_TYPE				CANOPEN_UNSIGNED8
#define ICU_WIDTH_CALIB_REQ_PERMISSIONS			CANOPEN_RW

#define ICU_WIDTH_CALIB_ADD_REQ_INDEX			0x2309
#define ICU_WIDTH_CALIB_ADD_REQ_SUBINDEX		0
#define ICU_WIDTH_CALIB_ADD_REQ_TYPE			CANOPEN_UNSIGNED16
#define ICU_WIDTH_CALIB_ADD_REQ_PERMISSIONS		CANOPEN_WO

#define ICU_WIDTH_CALIB_CLEAR_REQ_INDEX			0x230A
#define ICU_WIDTH_CALIB_CLEAR_REQ_SUBINDEX		0
#define ICU_WIDTH_CALIB_CLEAR_REQ_TYPE			CANOPEN_UNSIGNED8
#define ICU_WIDTH_CALIB_CLEAR_REQ_PERMISSIONS	CANOPEN_WO


#define ICU_VOL_DM3_INDEX						0x230B
#define ICU_VOL_DM3_SUBINDEX					0
#define ICU_VOL_DM3_TYPE						CANOPEN_UNSIGNED32
#define ICU_VOL_DM3_PERMISSIONS					CANOPEN_RW

#define ICU_VOL_RESET_INDEX						0x230C
#define ICU_VOL_RESET_SUBINDEX					0
#define ICU_VOL_RESET_TYPE						CANOPEN_UNSIGNED8
#define ICU_VOL_RESET_PERMISSIONS				CANOPEN_WO


#define ICU_FSB_INDEX_OFFSET					0x1000

#define ICU_HCU_INDEX_OFFSET					0x2000


#endif /* CAN_ICU_H_ */
