/*
 * csb.h
 *
 *  Created on: Aug 2, 2017
 *      Author: usevolt
 */

#ifndef CAN_CSB_H_
#define CAN_CSB_H_


/// @file: Defines the UW ceiling supply board CANopen interface.

#include <stdint.h>





#define CSB_NODE_ID					7




/// @brief: Defines all CSB's EMCY message data values.
/// All EMCY messages belong to device specific EMCY error code category (0xFF00)
typedef enum {
	CSB_EMCY_WORK_LIGHT_OVERCURRENT = (CSB_NODE_ID << 16),
	CSB_EMCY_WORK_LIGHT_FAULT,
	CSB_EMCY_DRIVE_LIGHT_OVERCURRENT,
	CSB_EMCY_DRIVE_LIGHT_FAULT,
	CSB_EMCY_BACK_LIGHT_OVERCURRENT,
	CSB_EMCY_BACK_LIGHT_FAULT,
	CSB_EMCY_IN_LIGHT_OVERCURRENT,
	CSB_EMCY_IN_LIGHT_FAULT,
	CSB_EMCY_BEACON_OVERCURRENT,
	CSB_EMCY_BEACON_FAULT,
	CSB_EMCY_WIPER_OVERCURRENT,
	CSB_EMCY_WIPER_FAULT,
	CSB_EMCY_COOLER_OVERCURRENT,
	CSB_EMCY_COOLER_FAULT,
	// deprecated, moved to ESB
	CSB_EMCY_OILCOOLER_OVERCURRENT,
	CSB_EMCY_OILCOOLER_FAULT,
	CSB_EMCY_COUNT
} csb_emcy_e;




// CSB OBJECT DICTIONARY ENTRIES


#define CSB_TOTAL_CURRENT_INDEX				0x2000
#define CSB_TOTAL_CURRENT_SUBINDEX			0
#define CSB_TOTAL_CURRENT_TYPE				CANOPEN_UNSIGNED16
#define CSB_TOTAL_CURRENT_PERMISSIONS		CANOPEN_RO

#define CSB_WORK_LIGHT_STATUS_INDEX			0x2100
#define CSB_WORK_LIGHT_STATUS_SUBINDEX		0
#define CSB_WORK_LIGHT_STATUS_TYPE			CANOPEN_UNSIGNED8
#define CSB_WORK_LIGHT_STATUS_PERMISSIONS	CANOPEN_RW

#define CSB_WORK_LIGHT_CURRENT_INDEX		0x2101
#define CSB_WORK_LIGHT_CURRENT_SUBINDEX		0
#define CSB_WORK_LIGHT_CURRENT_TYPE			CANOPEN_UNSIGNED16
#define CSB_WORK_LIGHT_CURRENT_PERMISSIONS	CANOPEN_RO

#define CSB_DRIVE_LIGHT_STATUS_INDEX		0x2110
#define CSB_DRIVE_LIGHT_STATUS_SUBINDEX		0
#define CSB_DRIVE_LIGHT_STATUS_TYPE			CANOPEN_UNSIGNED8
#define CSB_DRIVE_LIGHT_STATUS_PERMISSIONS	CANOPEN_RW

#define CSB_DRIVE_LIGHT_CURRENT_INDEX		0x2111
#define CSB_DRIVE_LIGHT_CURRENT_SUBINDEX	0
#define CSB_DRIVE_LIGHT_CURRENT_TYPE		CANOPEN_UNSIGNED16
#define CSB_DRIVE_LIGHT_CURRENT_PERMISSIONS	CANOPEN_RO

#define CSB_BACK_LIGHT_STATUS_INDEX			0x2120
#define CSB_BACK_LIGHT_STATUS_SUBINDEX		0
#define CSB_BACK_LIGHT_STATUS_TYPE			CANOPEN_UNSIGNED8
#define CSB_BACK_LIGHT_STATUS_PERMISSIONS	CANOPEN_RW

#define CSB_BACK_LIGHT_CURRENT_INDEX		0x2121
#define CSB_BACK_LIGHT_CURRENT_SUBINDEX		0
#define CSB_BACK_LIGHT_CURRENT_TYPE			CANOPEN_UNSIGNED16
#define CSB_BACK_LIGHT_CURRENT_PERMISSIONS	CANOPEN_RO

#define CSB_IN_LIGHT_STATUS_INDEX			0x2130
#define CSB_IN_LIGHT_STATUS_SUBINDEX		0
#define CSB_IN_LIGHT_STATUS_TYPE			CANOPEN_UNSIGNED8
#define CSB_IN_LIGHT_STATUS_PERMISSIONS		CANOPEN_RW

#define CSB_IN_LIGHT_CURRENT_INDEX			0x2131
#define CSB_IN_LIGHT_CURRENT_SUBINDEX		0
#define CSB_IN_LIGHT_CURRENT_TYPE			CANOPEN_UNSIGNED16
#define CSB_IN_LIGHT_CURRENT_PERMISSIONS	CANOPEN_RO

#define CSB_BEACON_STATUS_INDEX				0x2140
#define CSB_BEACON_STATUS_SUBINDEX			0
#define CSB_BEACON_STATUS_TYPE				CANOPEN_UNSIGNED8
#define CSB_BEACON_STATUS_PERMISSIONS		CANOPEN_RW

#define CSB_BEACON_CURRENT_INDEX			0x2141
#define CSB_BEACON_CURRENT_SUBINDEX			0
#define CSB_BEACON_CURRENT_TYPE				CANOPEN_UNSIGNED16
#define CSB_BEACON_CURRENT_PERMISSIONS		CANOPEN_RO

#define CSB_BEACON_ENABLED_INDEX			0x2142
#define CSB_BEACON_ENABLED_SUBINDEX			0
#define CSB_BEACON_ENABLED_TYPE				CANOPEN_UNSIGNED8
#define CSB_BEACON_ENABLED_PERMISSIONS		CANOPEN_RW


/// @brief: Defines the maximum wiper speed. Greater values
/// than this should not be written.
#define CSB_WIPER_MAX_SPEED					100

#define CSB_WIPER_STATUS_INDEX				0x2150
#define CSB_WIPER_STATUS_SUBINDEX			0
#define CSB_WIPER_STATUS_TYPE				CANOPEN_UNSIGNED8
#define CSB_WIPER_STATUS_PERMISSIONS		CANOPEN_RO

#define CSB_WIPER_CURRENT_INDEX				0x2151
#define CSB_WIPER_CURRENT_SUBINDEX			0
#define CSB_WIPER_CURRENT_TYPE				CANOPEN_UNSIGNED16
#define CSB_WIPER_CURRENT_PERMISSIONS		CANOPEN_RO

#define CSB_WIPER_SPEED_INDEX				0x2152
#define CSB_WIPER_SPEED_SUBINDEX			0
#define CSB_WIPER_SPEED_TYPE				CANOPEN_UNSIGNED8
#define CSB_WIPER_SPEED_PERMISSIONS			CANOPEN_RW

#define CSB_WIPER_REQ_INDEX					0x2153
#define CSB_WIPER_REQ_SUBINDEX				0
#define CSB_WIPER_REQ_TYPE					CANOPEN_SIGNED8
#define CSB_WIPER_REQ_PERMISSIONS			CANOPEN_RW

#define CSB_WIPER_POL_INDEX					0x2154
#define CSB_WIPER_POL_SUBINDEX				0
#define CSB_WIPER_POL_TYPE					CANOPEN_UNSIGNED8
#define CSB_WIPER_POL_PERMISSIONS			CANOPEN_RW

#define CSB_COOLER_STATUS_INDEX				0x2160
#define CSB_COOLER_STATUS_SUBINDEX			0
#define CSB_COOLER_STATUS_TYPE				CANOPEN_UNSIGNED8
#define CSB_COOLER_STATUS_PERMISSIONS		CANOPEN_RW

#define CSB_COOLER_CURRENT_INDEX			0x2161
#define CSB_COOLER_CURRENT_SUBINDEX			0
#define CSB_COOLER_CURRENT_TYPE				CANOPEN_UNSIGNED16
#define CSB_COOLER_CURRENT_PERMISSIONS		CANOPEN_RO

#define CSB_COOLER_P_INDEX					0x2162
#define CSB_COOLER_P_SUBINDEX				0
#define CSB_COOLER_P_TYPE					CANOPEN_UNSIGNED8
#define CSB_COOLER_P_PERMISSIONS			CANOPEN_RO


// RX data objects

#define CSB_ESB_OIL_TEMP_INDEX				0x2500
#define CSB_ESB_OIL_TEMP_SUBINDEX			0
#define CSB_ESB_OIL_TEMP_TYPE				CANOPEN_UNSIGNED8
#define CSB_ESB_OIL_TEMP_PERMISSIONS		CANOPEN_WO

#define CSB_FSB_EMCY_INDEX					0x2510
#define CSB_FSB_EMCY_SUBINDEX				0
#define CSB_FSB_EMCY_TYPE					CANOPEN_UNSIGNED8
#define CSB_FSB_EMCY_PERMISSIONS			CANOPEN_WO



#endif /* CAN_CSB_H_ */
