/* 
 * This file is part of the uv_hal distribution (www.usevolt.fi).
 * Copyright (c) 2017 Usevolt Oy.
 * 
 * This program is free software: you can redistribute it and/or modify  
 * it under the terms of the GNU General Public License as published by  
 * the Free Software Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful, but 
 * WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License 
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
*/


#ifndef CAN_ICU_H_
#define CAN_ICU_H_


/// @file: Defines the UW ceiling supply board CANopen interface.

#include <stdint.h>






#define ICU_NODE_ID					0xA






/// @brief: Defines all ICU's EMCY message data values.
/// All EMCY messages belong to device specific EMCY error code category (0xFF00)
typedef enum {
	ICU_EMCY_OUT1_OVERCURRENT,
	ICU_EMCY_OUT1_FAULT,
	ICU_EMCY_OUT2_OVERCURRENT,
	ICU_EMCY_OUT2_FAULT,
	ICU_EMCY_OUT3_OVERCURRENT,
	ICU_EMCY_OUT3_FAULT,
	ICU_EMCY_OUT4_OVERCURRENT,
	ICU_EMCY_OUT4_FAULT,
	ICU_EMCY_OUT5_OVERCURRENT,
	ICU_EMCY_OUT5_FAULT,
	ICU_EMCY_OUT6_OVERCURRENT,
	ICU_EMCY_OUT6_FAULT,
	ICU_EMCY_OUT7_OVERCURRENT,
	ICU_EMCY_OUT7_FAULT,
	ICU_EMCY_COUNT
} icu_emcy_e;




// ICU OBJECT DICTIONARY ENTRIES


#define ICU_TOTAL_CURRENT_INDEX					0x2000
#define ICU_TOTAL_CURRENT_SUBINDEX				0
#define ICU_TOTAL_CURRENT_TYPE					CANOPEN_UNSIGNED16
#define ICU_TOTAL_CURRENT_PERMISSIONS			CANOPEN_RO

#define ICU_BLADE_OPEN_CONF_INDEX				0x2010
#define ICU_BLADE_OPEN_CONF_ARRAY_MAX_SIZE		5
#define ICU_BLADE_OPEN_CONF_TYPE				CANOPEN_ARRAY16
#define ICU_BLADE_OPEN_CONF_PERMISSIONS			CANOPEN_RW

#define ICU_BLADE_OPEN_REQ_INDEX				0x2011
#define ICU_BLADE_OPEN_REQ_SUBINDEX				0
#define ICU_BLADE_OPEN_REQ_TYPE					CANOPEN_SIGNED8
#define ICU_BLADE_OPEN_REQ_PERMISSIONS			CANOPEN_RW

#define ICU_FEED_OPEN_CONF_INDEX				0x2020
#define ICU_FEED_OPEN_CONF_ARRAY_MAX_SIZE		5
#define ICU_FEED_OPEN_CONF_TYPE					CANOPEN_ARRAY16
#define ICU_FEED_OPEN_CONF_PERMISSIONS			CANOPEN_RW

#define ICU_FEED_OPEN_REQ_INDEX					0x2021
#define ICU_FEED_OPEN_REQ_SUBINDEX				0
#define ICU_FEED_OPEN_REQ_TYPE					CANOPEN_SIGNED8
#define ICU_FEED_OPEN_REQ_PERMISSIONS			CANOPEN_RW

#define ICU_FEED_CONF_INDEX						0x2030
#define ICU_FEED_CONF_ARRAY_MAX_SIZE			5
#define ICU_FEED_CONF_TYPE						CANOPEN_ARRAY16
#define ICU_FEED_CONF_PERMISSIONS				CANOPEN_RW

#define ICU_FEED_REQ_INDEX						0x2031
#define ICU_FEED_REQ_SUBINDEX					0
#define ICU_FEED_REQ_TYPE						CANOPEN_SIGNED8
#define ICU_FEED_REQ_PERMISSIONS				CANOPEN_RW

#define ICU_SAW_CONF_INDEX						0x2040
#define ICU_SAW_CONF_ARRAY_MAX_SIZE				5
#define ICU_SAW_CONF_TYPE						CANOPEN_ARRAY16
#define ICU_SAW_CONF_PERMISSIONS				CANOPEN_RW

#define ICU_SAW_REQ_INDEX						0x2041
#define ICU_SAW_REQ_SUBINDEX					0
#define ICU_SAW_REQ_TYPE						CANOPEN_SIGNED8
#define ICU_SAW_REQ_PERMISSIONS					CANOPEN_RW

#define ICU_SAW_OUT_SPEED_INDEX					0x2042
#define ICU_SAW_OUT_SPEED_SUBINDEX				0
#define ICU_SAW_OUT_SPEED_TYPE					CANOPEN_UNSIGNED16
#define ICU_SAW_OUT_SPEED_PERMISSIONS			CANOPEN_RW

#define ICU_SAW_IN_SPEED_INDEX					0x2043
#define ICU_SAW_IN_SPEED_SUBINDEX				0
#define ICU_SAW_IN_SPEED_TYPE					CANOPEN_UNSIGNED16
#define ICU_SAW_IN_SPEED_PERMISSIONS			CANOPEN_RW

#define ICU_TILT_CONF_INDEX						0x2050
#define ICU_TILT_CONF_ARRAY_MAX_SIZE			5
#define ICU_TILT_CONF_TYPE						CANOPEN_ARRAY16
#define ICU_TILT_CONF_PERMISSIONS				CANOPEN_RW

#define ICU_TILT_REQ_INDEX						0x2051
#define ICU_TILT_REQ_SUBINDEX					0
#define ICU_TILT_REQ_TYPE						CANOPEN_SIGNED8
#define ICU_TILT_REQ_PERMISSIONS				CANOPEN_RW

#define ICU_ALL_OPEN_CONF_INDEX					0x2060
#define ICU_ALL_OPEN_CONF_ARRAY_MAX_SIZE		5
#define ICU_ALL_OPEN_CONF_TYPE					CANOPEN_ARRAY16
#define ICU_ALL_OPEN_CONF_PERMISSIONS			CANOPEN_RW

#define ICU_ALL_OPEN_REQ_INDEX					0x2061
#define ICU_ALL_OPEN_REQ_SUBINDEX				0
#define ICU_ALL_OPEN_REQ_TYPE					CANOPEN_SIGNED8
#define ICU_ALL_OPEN_REQ_PERMISSIONS			CANOPEN_RW


#define ICU_IMPL1_REQ_INDEX						0x2100
#define ICU_IMPL1_REQ_SUBINDEX					0
#define ICU_IMPL1_REQ_TYPE						CANOPEN_SIGNED16
#define ICU_IMPL1_REQ_PERMISSIONS				CANOPEN_RO

#define ICU_IMPL2_REQ_INDEX						0x2101
#define ICU_IMPL2_REQ_SUBINDEX					0
#define ICU_IMPL2_REQ_TYPE						CANOPEN_SIGNED16
#define ICU_IMPL2_REQ_PERMISSIONS				CANOPEN_RO

#define ICU_TARGET_LEN_UM_INDEX					0x2102
#define ICU_TARGET_LEN_UM_SUBINDEX				0x0
#define ICU_TARGET_LEN_UM_TYPE					CANOPEN_SIGNED32
#define ICU_TARGET_LEN_UM_PERMISSIONS			CANOPEN_RW

#define ICU_LEN_CALIB_INDEX						0x2103
#define ICU_LEN_CALIB_SUBINDEX					0
#define ICU_LEN_CALIB_TYPE						CANOPEN_UNSIGNED16
#define ICU_LEN_CALIB_PERMISSIONS				CANOPEN_RW

#define ICU_TARGET_REACHED_INDEX				0x2104
#define ICU_TARGET_REACHED_SUBINDEX				0
#define ICU_TARGET_REACHED_TYPE					CANOPEN_UNSIGNED8
#define ICU_TARGET_REACHED_PERMISSIONS			CANOPEN_RO

#define ICU_LEN_UM_INDEX						0x2105
#define ICU_LEN_UM_SUBINDEX						0
#define ICU_LEN_UM_TYPE							CANOPEN_SIGNED32
#define ICU_LEN_UM_PERMISSIONS					CANOPEN_RO


#define ICU_WIDTH_MM_INDEX						0x2108
#define ICU_WIDTH_MM_SUBINDEX					0
#define ICU_WIDTH_MM_TYPE						CANOPEN_UNSIGNED32
#define ICU_WIDTH_MM_PERMISSIONS				CANOPEN_RO

#define ICU_VOLUME_INDEX						0x2109
#define ICU_VOLUME_SUBINDEX						0
#define ICU_VOLUME_TYPE							CANOPEN_UNSIGNED32
#define ICU_VOLUME_PERMISSIONS					CANOPEN_RO

#define ICU_FEED_FINETUNE_WAIT_INDEX			0x2110
#define ICU_FEED_FINETUNE_WAIT_SUBINDEX			0
#define ICU_FEED_FINETUNE_WAIT_TYPE				CANOPEN_UNSIGNED16
#define ICU_FEED_FINETUNE_WAIT_PERMISSIONS		CANOPEN_RW

#define ICU_FEED_FINETUNE_FEED_INDEX			0x2111
#define ICU_FEED_FINETUNE_FEED_SUBINDEX			0
#define ICU_FEED_FINETUNE_FEED_TYPE				CANOPEN_UNSIGNED16
#define ICU_FEED_FINETUNE_FEED_PERMISSIONS		CANOPEN_RW

#define ICU_FEED_PARALLEL_WAIT_INDEX			0x2112
#define ICU_FEED_PARALLEL_WAIT_SUBINDEX			0
#define ICU_FEED_PARALLEL_WAIT_TYPE				CANOPEN_UNSIGNED16
#define ICU_FEED_PARALLEL_WAIT_PERMISSIONS		CANOPEN_RW

#define ICU_FEED_PARALLEL_FEED_INDEX			0x2113
#define ICU_FEED_PARALLEL_FEED_SUBINDEX			0
#define ICU_FEED_PARALLEL_FEED_TYPE				CANOPEN_UNSIGNED16
#define ICU_FEED_PARALLEL_FEED_PERMISSIONS		CANOPEN_RW

#define ICU_SAW_POSITION_INDEX					0x2120
#define ICU_SAW_POSITION_SUBINDEX				0
#define ICU_SAW_POSITION_TYPE					CANOPEN_UNSIGNED8
#define ICU_SAW_POSITION_PERMISSIONS			CANOPEN_RO

#define ICU_SAW_POS_UNKNOWN_INDEX				0x2121
#define ICU_SAW_POS_UNKNOWN_SUBINDEX			0
#define ICU_SAW_POS_UNKNOWN_TYPE				CANOPEN_UNSIGNED8
#define ICU_SAW_POS_UNKNOWN_PERMISSIONS			CANOPEN_RO

#define ICU_RESET_VOL_INDEX						0x2130
#define ICU_RESET_VOL_SUBINDEX					0
#define ICU_RESET_VOL_TYPE						CANOPEN_UNSIGNED8
#define ICU_RESET_VOL_PERMISSIONS				CANOPEN_RW


#define ICU_SAVE_INDEX							0x2500
#define ICU_SAVE_SUBINDEX						0
#define ICU_SAVE_TYPE							CANOPEN_UNSIGNED8
#define ICU_SAVE_PERMISSIONS					CANOPEN_WO



// objects to hold other nodes data
#define ICU_FSB_IGNKEY_INDEX					0x2A00
#define ICU_FSB_IGNKEY_SUBINDEX					0
#define ICU_FSB_IGNKEY_PERMISSIONS				CANOPEN_WO

#define ICU_FSB_EMCY_INDEX						0x2A01
#define ICU_FSB_EMCY_SUBINDEX					0
#define ICU_FSB_EMCY_PERMISSIONS				CANOPEN_WO

#define ICU_ECU_HYDR_PRESSURE_INDEX				0x2A03
#define ICU_ECU_HYDR_PRESSURE_SUBINDEX			0
#define ICU_ECU_HYDR_PRESSURE_PERMISSIONS		CANOPEN_WO
#define ICU_ECU_HYDR_PRESSURE_TYPE				CANOPEN_UNSIGNED16


#endif /* CAN_ICU_H_ */
